	for (var i = 104; i < 700 ; i++) {
		telephone = ('000' + i).slice(-4);
		$.ajax({
			url: "http://192.168.10.21/red/scom01/patient/savepatient?rdm=621461af90cad",
			type: "POST",
			async: false,
			data: {
				"YII_CSRF_TOKEN": "782a77964c15260f111b662a2196b30cb865a676",
				"patient_id": "-1",
				"section_name": "",
				"patient_name": "aselenium" + telephone,
				"patient_name2": "aselenium" + telephone,
				"patient_kana": "aselenium" + telephone,
				"patient_kana2": "aselenium" + telephone,
				"patient_birthday": "2018/01/01",
				"patient_tel": "052700" + telephone,
				"patient_postnum": "460-0001",
				"patient_address": "0527894561",
				"patient_cellphone": "052700" + telephone,
				"patient_mail": "tung@gmail.com",
				"patient_milook_mail": "",
				"patient_sick_name": "",
				"patient_sick_status": "",
				"patient_sick_history": "",
				"patient_sick_medicine": "",
				"patient_sick_other": "",
				"patient_sick_infection_memo": "",
				"patient_meal_other": "",
				"patient_meal_memo": "",
				"patient_dentistcare_other": "",
				"patient_dentistcare_memo": "",
				"patient_move_other": "",
				"patient_move_memo": "",
				"patient_bathing_memo": "",
				"patient_excretion_memo": "",
				"patient_sleep_status": "",
				"patient_sleep_memo": "",
				"patient_state": "0",
				"patient_sex": "1",
				"patient_memo": "",
				"query_exclusion": "0",
				"patient_user[0][user_group_id]": "3",
				"patient_user[0][group_flag]": "0",
				"patient_user[1][user_group_id]": "4",
				"patient_user[1][group_flag]": "0",
				"patient_user[2][user_group_id]": "6",
				"patient_user[2][group_flag]": "0",
				"patient_syujii_hukusyujii[0][option]": "0",
				"patient_syujii_hukusyujii[0][id]": "3",
				"patient_syujii_hukusyujii[1][option]": "0",
				"patient_syujii_hukusyujii[1][id]": "4",
				"patient_syujii_hukusyujii[2][option]": "0",
				"patient_syujii_hukusyujii[2][id]": "6",
				"patient_document_r": "0",
				"patient_document_w": "0"
			},
			success: function () {
				console.log(i);
			}
		});
	}